CREATE TABLE IF NOT EXISTS KodUser (
  uid BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(80) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  balance DECIMAL(12,2) NOT NULL DEFAULT 10000.00,
  phone VARCHAR(20) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'customer',
  PRIMARY KEY (uid)
);

CREATE TABLE IF NOT EXISTS UserToken (
  tid BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  token TEXT NOT NULL,
  uid BIGINT UNSIGNED NOT NULL,
  expiry DATETIME NOT NULL,
  PRIMARY KEY (tid),
  INDEX idx_user_token_uid (uid),
  CONSTRAINT fk_user_token_uid
    FOREIGN KEY (uid)
    REFERENCES KodUser(uid)
    ON DELETE CASCADE
);
